### ISSUE TITLE
Support for extras and for path

### ISSUE THREAD

**Issue by cropr** [jla524/requirements#5]
Support for 2 additional features wouyld be welcome

1) support for "extras": in the pyproject.toml one can have a dependency like

`python-jose = {extras = ["cryptography"], version = "^3.3.0"}`

which should be converted to 

`python-jose[cryptography]==3.3.0`

2) The same applies for dependencies that are defined with local path names

`mylib = {path = "libs/mylib-3.0.4-py3-none-any.whl"}`

which should be converted to

`libs/mylib-3.0.4-py3-none-any.whl`

**Comment by jla524** [comment]
Thanks for the suggestion! I've added these features in the most recent commit.
